data:
	gcc -Wall -o main main.c
	./main data
	
nadawca:
	gcc -Wall -o main main.c
	./main nadawca
	
wyslij:
	gcc -Wall -o main main.c
	./main 'test@test.com' 'Hello World' 'Hello world - test mail.'
	
clean:
	rm -f main
