compile:
	gcc -Wall main.c -o main -lpthread -lm

test1:
	./main 10 numbers test/balloons.ascii.pgm test/neg-balloons.ascii.pgm
	
test2:
	./main 10 blocks test/surf.ascii.pgm test/neg-surf.ascii.pgm
	
test3:
	./main 2 blocks test/totem.ascii.pgm test/neg-totem.ascii.pgm
